server:
  port: 8080

spring:
  main:
    time-zone: UTC
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
  security:
    user:
      name: admin
      password: admin

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
